language: python
python:
  - "3.6"
cache: pip
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install pandoc
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install coveralls

install:
  - python setup.py install

script:
  - pytest tests

env:
  global:
    
    # Doctr deploy key for srush/miniTorch
    - secure: "XP2ZPwssUsdFe4kNeRZ46ZmxdNzjn9W2Ho7MwwynTiHSQEQK9idaBb0F9jeBMMA3Cq2J/Gf2BaCJihsjNxCP1
jX4781898kcB8UJXlQQYnp+yena57d/h0paH4k8YF2DO9N6LyUV43TBxFm658mWDxx2zJ+wB2SsO8ii+XMr4MmHxII4jbN4QfUdUaGUv
Y1slXl/HqrXkNEVmr9QJyKDE8b+iYnEuJLreLwoqgM6dyG9splEl4ZA8bkbjSUVCosiu64rnucVt5yI/94VCkbCDmXRIz24Ryyn4nN/V
TtitUEZFXAY617nUoYhY3zo0LWQEdyHPePu0ketEWmzg7LSLNvPfk0m50w2IogmaxAP3NVMEFWe/Y6z1pd76+VrO+7MBYY2T0SaRIfhn
HVMwSjRtsVqw7pQOUkwE9EvW07a/FIqVR9XJx+qKEq9SeKN4arPjQFlP/84cQoWg4h1CqFniEsb/OT2cRBpO25qr+VvVopkfZ8ryQAAq
K6ExGjR0B0IdHrM2nDjRLiwLvnZHkbBYz91P7e2WbVqbbJtuXUzCS8GYE1A9iLXLYI5KU7I9MFuEkLL1BFTi+pPzcA35+U99izJsmJPz
blwycuV2rx60m/XFe3YAlrt7oCkQwMVzXrsIfwqWcwU+yq9RlWVVHjm5BvTNXHLsgZIld7OkIX1zmU="                       


matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 pep8-naming
      script: flake8 --ignore "N801, E203, E266, E501, W503, F812, E741, N803, N802, N806" minitorch/ tests/
    - python: "3.6"
      install:
        - python setup.py install
        - pip install doctr
      script:
        - pip install -r docs/requirements.txt
        - cd docs/; make html; cd ..
        - set -e
        - doctr deploy --built-docs docs/build/html/ .
